{
 "title": "DevOps FastAPI Platform",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Application Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests/sec",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 1, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (namespace) (\r\n  rate(http_requests_total{\r\n    job=~\"fastapi-app-.*-backend\",\r\n    handler!=\"/metrics\"\r\n  }[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request count by handler",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 1, "w": 12, "h": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (handler) (\r\n  rate(http_requests_total{\r\n    job=~\"fastapi-app-.*-backend\"\r\n  }[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 9, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\r\n  rate(http_requests_total{\r\n    job=~\"fastapi-app-.*-backend\",\r\n    status!~\"2xx|3xx\",\r\n    handler!=\"/metrics\"\r\n  }[5m])\r\n)\r\n/\r\nsum by (namespace) (\r\n  rate(http_requests_total{\r\n    job=~\"fastapi-app-.*-backend\",\r\n    handler!=\"/metrics\"\r\n  }[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Memory usage",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 9, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n  process_resident_memory_bytes{\n    job=~\"fastapi-app-.*-backend\"\n  }\n)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "P95 latency",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 17, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, namespace) (\r\n    rate(\r\n      http_request_duration_seconds_bucket{\r\n        job=~\"fastapi-app-.*-backend\",\r\n        handler!=\"/metrics\"\r\n      }[5m]\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend CPU Usage",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 17, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (namespace) (\n  rate(process_cpu_seconds_total{\n    job=~\"fastapi-app-.*-backend\"\n  }[5m])\n)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 26, "w": 24, "h": 6 },
   "targets": [
    {
     "expr": "sum(max by (namespace, pod, container)\r\n(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m))\r\nby (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 32, "w": 24, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\r\n  max by (namespace, pod, container) (\r\n    container_memory_rss{\r\n      job=\"kubelet\",\r\n      metrics_path=\"/metrics/cadvisor\",\r\n      container!=\"\",\r\n      image!=\"\"\r\n    }\r\n  )\r\n) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "CPU Utilisation",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 39, "w": 12, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  (\n    instance:node_cpu_utilisation:rate5m{job=\"node-exporter\"}\n    *\n    instance:node_num_cpu:sum{job=\"node-exporter\"}\n  ) != 0\n)\n/\nscalar(sum(instance:node_num_cpu:sum{job=\"node-exporter\"}))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 39, "w": 12, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  instance:node_memory_utilisation:ratio{job=\"node-exporter\"}\n  /\n  scalar(count(instance:node_memory_utilisation:ratio{job=\"node-exporter\"}))\n) != 0",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Disk Space Utilisation",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 46, "w": 24, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without (device) (\n  max without (fstype, mountpoint) (\n    (\n      node_filesystem_size_bytes{job=\"node-exporter\", fstype!=\"\", mountpoint!=\"\"}\n      -\n      node_filesystem_avail_bytes{job=\"node-exporter\", fstype!=\"\", mountpoint!=\"\"}\n    ) != 0\n  )\n)\n/\nscalar(\n  sum(\n    max without (fstype, mountpoint) (\n      node_filesystem_size_bytes{job=\"node-exporter\", fstype!=\"\", mountpoint!=\"\"}\n    )\n  )\n)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Network Utilisation (Bytes Receive/Transmit)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 53, "w": 12, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "instance:node_network_receive_bytes_excluding_lo:rate5m{job=\"node-exporter\"} != 0",
     "legendFormat": "{{ instance }} Receive"
    },
    {
     "expr": "instance:node_network_transmit_bytes_excluding_lo:rate5m{job=\"node-exporter\"} != 0",
     "legendFormat": "{{ instance }} Transmit"
    }
   ]
  },
  { "title": "Kubernetes Workload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 61, "w": 24, "h": 7 },
   "targets": [
    {
     "expr": "sum(\n  max by (cluster, namespace, pod, container)(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m\n  )\n* on(cluster, namespace, pod)\n  group_left(workload, workload_type)\n  namespace_workload_pod:kube_pod_owner:relabel\n) by (workload, workload_type)",
     "legendFormat": "{{workload}} - {{workload_type}}"
    },
    {
     "expr": "scalar(max(kube_resourcequota{type=\"hard\", resource=~\"requests.cpu|cpu\"}))",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(max(kube_resourcequota{type=\"hard\", resource=~\"limits.cpu\"}))",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 68, "w": 24, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n    max by (cluster, namespace, pod, container)(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", image!=\"\"})\n  * on(cluster, namespace, pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel\n) by (workload, workload_type)\n",
     "legendFormat": "{{workload}} - {{workload_type}}"
    },
    {
     "expr": "scalar(max(kube_resourcequota{type=\"hard\",resource=~\"requests.memory|memory\"}))",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(max(kube_resourcequota{type=\"hard\",resource=~\"limits.memory\"}))",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 75, "w": 24, "h": 7 },
   "targets": [
    {
     "expr": "count(namespace_workload_pod:kube_pod_owner:relabel) by (workload, workload_type)"
    },
    {
     "expr": "sum(\n  max by (cluster, namespace, pod, container)(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m)\n* on(cluster, namespace, pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel\n) by (workload, workload_type)\n"
    },
    {
     "expr": "sum(\n  max by (cluster, namespace, pod, container)(kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"cpu\"})\n* on(cluster, namespace, pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel\n) by (workload, workload_type)\n"
    },
    {
     "expr": "sum(\n  max by (cluster, namespace, pod, container)(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m)\n* on(cluster, namespace, pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel\n) by (workload, workload_type)\n/sum(\n  max by (cluster, namespace, pod, container)(kube_pod_container_resource_requests{job=\"kube-state-metrics\", resource=\"cpu\"})\n* on(cluster, namespace, pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel\n) by (workload, workload_type)\n"
    },
    {
     "expr": "sum(\n  max by (cluster, namespace, pod, container)(kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"cpu\"})\n* on(cluster, namespace, pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel\n) by (workload, workload_type)\n"
    },
    {
     "expr": "sum(\n  max by (cluster, namespace, pod, container)(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m)\n* on(cluster, namespace, pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel\n) by (workload, workload_type)\n/sum(\n  max by (cluster, namespace, pod, container)(kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"cpu\"})\n* on(cluster, namespace, pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel\n) by (workload, workload_type)\n"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 82, "w": 24, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "count(namespace_workload_pod:kube_pod_owner:relabel) by (workload, workload_type)"
    },
    {
     "expr": "sum(\n    max by (cluster, namespace, pod, container)(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", image!=\"\"})\n  * on(cluster, namespace, pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel\n) by (workload, workload_type)\n"
    },
    {
     "expr": "sum(\n  max by (cluster, namespace, pod, container)(\n    kube_pod_container_resource_requests{\n      job=\"kube-state-metrics\",\n      resource=\"memory\"\n    }\n  )\n* on(cluster, namespace, pod)\n  group_left(workload, workload_type)\n  namespace_workload_pod:kube_pod_owner:relabel\n) by (workload, workload_type)"
    },
    {
     "expr": "sum(\n  max by (cluster, namespace, pod, container)(\n    container_memory_working_set_bytes{\n      job=\"kubelet\",\n      metrics_path=\"/metrics/cadvisor\",\n      container!=\"\",\n      image!=\"\"\n    }\n  )\n* on(cluster, namespace, pod)\n  group_left(workload, workload_type)\n  namespace_workload_pod:kube_pod_owner:relabel\n) by (workload, workload_type)\n/\nsum(\n  max by (cluster, namespace, pod, container)(\n    kube_pod_container_resource_requests{\n      job=\"kube-state-metrics\",\n      resource=\"memory\"\n    }\n  )\n* on(cluster, namespace, pod)\n  group_left(workload, workload_type)\n  namespace_workload_pod:kube_pod_owner:relabel\n) by (workload, workload_type)"
    },
    {
     "expr": "sum(\n  max by (cluster, namespace, pod, container)(\n    kube_pod_container_resource_limits{\n      job=\"kube-state-metrics\",\n      resource=\"memory\"\n    }\n  )\n* on(cluster, namespace, pod)\n  group_left(workload, workload_type)\n  namespace_workload_pod:kube_pod_owner:relabel\n) by (workload, workload_type)"
    },
    {
     "expr": "sum(\n  max by (cluster, namespace, pod, container)(\n    container_memory_working_set_bytes{\n      job=\"kubelet\",\n      metrics_path=\"/metrics/cadvisor\",\n      container!=\"\",\n      image!=\"\"\n    }\n  )\n* on(cluster, namespace, pod)\n  group_left(workload, workload_type)\n  namespace_workload_pod:kube_pod_owner:relabel\n) by (workload, workload_type)\n/\nsum(\n  max by (cluster, namespace, pod, container)(\n    kube_pod_container_resource_limits{\n      job=\"kube-state-metrics\",\n      resource=\"memory\"\n    }\n  )\n* on(cluster, namespace, pod)\n  group_left(workload, workload_type)\n  namespace_workload_pod:kube_pod_owner:relabel\n) by (workload, workload_type)"
    }
   ]
  },
  { "title": "Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "Targets Up",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 90, "w": 12, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cluster, job, instance) (\r\n  prometheus_sd_discovered_targets\r\n)",
     "legendFormat": "{{cluster}}:{{job}}:{{instance}}"
    }
   ]
  },
  {
   "title": "Scrape failures",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 90, "w": 8, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cluster, job, instance) (\n  rate(prometheus_target_scrapes_exceeded_body_size_limit_total[1m])\n)",
     "legendFormat": "exceeded body size limit: {{cluster}} {{job}} {{instance}}"
    },
    {
     "expr": "sum by (cluster, job, instance) (\n  rate(prometheus_target_scrapes_exceeded_sample_limit_total[1m])\n)",
     "legendFormat": "exceeded sample limit: {{cluster}} {{job}} {{instance}}"
    },
    {
     "expr": "sum by (cluster, job, instance) (\n  rate(prometheus_target_scrapes_sample_duplicate_timestamp_total[1m])\n)",
     "legendFormat": "duplicate timestamp: {{cluster}} {{job}} {{instance}}"
    },
    {
     "expr": "sum by (cluster, job, instance) (\n  rate(prometheus_target_scrapes_sample_out_of_bounds_total[1m])\n)",
     "legendFormat": "out of bounds: {{cluster}} {{job}} {{instance}}"
    },
    {
     "expr": "sum by (cluster, job, instance) (\n  rate(prometheus_target_scrapes_sample_out_of_order_total[1m])\n)",
     "legendFormat": "out of order: {{cluster}} {{job}} {{instance}}"
    }
   ]
  }
 ]
}