# Generated by Terraform - DO NOT EDIT

k8s_master_ip: "${master_ips[0]}"

k8s_master_ips:
%{ for ip in master_ips ~}
  - "${ip}"
%{ endfor ~}

k8s_worker_ips:
%{ for ip in worker_ips ~}
  - "${ip}"
%{ endfor ~}

k8s_hosts:
%{ for index, ip in master_ips ~}
  - ip: "${ip}"
    name: "master-${index + 1}"
%{ endfor ~}
%{ for index, ip in worker_ips ~}
  - ip: "${ip}"
    name: "worker-${index + 1}"
%{ endfor ~}

kube_api_vip: "${kube_api_vip}"
control_plane_endpoint: "{{ kube_api_vip }}:8443"

keepalived_interface: "eth0"
keepalived_auth_pass: "kubeha"

domain: "${domain}"
acme_email: "${acme_email}"