{{- if and .Values.adminer.enabled .Values.adminer.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-adminer
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "fastapi-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: adminer

  {{- with .Values.adminer.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  ingressClassName: {{ .Values.adminer.ingress.className }}

  rules:
    - host: {{ .Values.adminer.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-adminer
                port:
                  number: {{ .Values.adminer.service.port }}

  {{- if .Values.adminer.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.adminer.ingress.host }}
      secretName: {{ .Values.adminer.ingress.tls.secretName }}
  {{- end }}
{{- end }}