"""Add price and website to Item model

Revision ID: d7d7f7988f20
Revises: 1a31ce608336
Create Date: 2026-06-08 13:42:07.099941

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd7d7f7988f20'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('item', sa.Column('website', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'website')
    op.drop_column('item', 'price')
    # ### end Alembic commands ###
